---
- name: Dpkg options
  ansible.builtin.template:
    src: dpkg.j2
    dest: /etc/apt/apt.conf.d/80dpkg
    owner: root
    group: root
    mode: 0644
  when: apt_dpkg_config is defined
  tags:
    - apt
    - dpkg
