---
# tasks file for apt
- name: apt.conf
  template:
    src: "apt.conf.j2"
    dest: '/etc/apt/apt.conf'
    backup: 'yes'
    owner: root
    group: root
    mode: 0644
  when:
    - apt_codename is defined
  notify:
    - update cache
  tags:
    - apt
    - conf

- name: apt.conf
  file:
    path: '/etc/apt/apt.conf'
    state: absent
  when:
    - apt_codename is not defined
  notify:
    - update cache
  tags:
    - apt
    - conf

- name: sources.list
  template:
    src: "sources.list.{{ ansible_lsb['id'] }}.j2"
    dest: '/etc/apt/sources.list'
    backup: 'yes'
    owner: root
    group: root
    mode: 0644
  notify:
    - update cache
  tags:
    - apt
    - sources

- name: dpkg options
  template:
    src: 'dpkg_options.j2'
    dest: '/etc/apt/apt.conf.d/80dpkg'
  tags:
    - apt
    - dpkg
    - options

- name: check for noexec /tmp
  shell: 'grep -wq /tmp /etc/fstab && mount|grep -w /tmp|grep -q noexec 2>/dev/null'
  ignore_errors: true
  register: tmp_noexec
  tags:
    - apt
    - dpkg
    - tmp

- name: dpkg options for noexec /tmp
  template:
    src: 'dpkg_tmp.j2'
    dest: '/etc/apt/apt.conf.d/81dpkg'
  when: tmp_noexec is succeeded
  tags:
    - apt
    - dpkg
    - tmp

- name: network options
  template:
    src: network.j2
    dest: '/etc/apt/apt.conf.d/30network'
  when: proxy_env is defined
  tags:
    - apt
    - network

- name: remove dist-backports.list file if present
  file:
    path: '/etc/apt/sources.list.d/{{ apt_codename | default(ansible_distribution_release) }}-backports.list'
    state: absent
  notify:
    - update cache
  when:
    - apt_codename is defined
    - apt_backports is not defined or apt_backports|lower() in ['true','yes']
  tags:
    - apt
    - sources
    - backports

- name: backports
  template:
    src: backports.list.j2
    dest: '/etc/apt/sources.list.d/backports.list'
  notify:
    - update cache
  when:
    - apt_backports is defined
    - apt_backports|lower() in ['true','yes']
  tags:
    - apt
    - sources
    - backports

- name: remove backports.list
  file:
    path: '/etc/apt/sources.list.d/backports.list'
    state: absent
  notify:
    - update cache
  when:
    apt_backports is not defined or apt_backports|lower() in ['false','no']
  tags:
    - apt
    - sources
    - backports

- name: additional repositories
  apt_repository:
    filename: '{{ item.filename }}'
    repo: '{{ item.repo }}'
    state: '{{ item.state }}'
    update_cache: true
  loop: '{{ apt_repositories }}'
  when: apt_repositories is defined
  tags:
    - apt
    - sources
    - repositories

- name: "remove *-updates preferences"
  file:
    path: "/etc/apt/preferences.d/{% if apt_codename is defined %}{{ apt_codename }}{% elif apt_release is defined %}{{ apt_release }}{% else %}{{ ansible_lsb['codename'] }}{% endif %}-updates"
    state: absent
  notify:
    - gen caches
  when: apt_proposed_updates is not defined or apt_proposed_updates|lower() in ['false','no']
  tags:
    - apt
    - updates
    - preferences

- name: "allow {% if apt_codename is defined %}{{ apt_codename }}{% elif apt_release is defined %}{{ apt_release }}{% else %}{{ ansible_lsb['codename'] }}{% endif %}-updates via preferences"
  template:
    src: updates.preferences.j2
    dest: "/etc/apt/preferences.d/{% if apt_codename is defined %}{{ apt_codename }}{% elif apt_release is defined %}{{ apt_release }}{% else %}{{ ansible_lsb['codename'] }}{% endif %}-updates"
  notify:
    - gen caches
  when:
    - apt_proposed_updates is defined
    - apt_proposed_updates|lower() in ['true','yes']
  tags:
    - apt
    - updates
    - preferences

- name: apt-daily timer override dir
  file:
    path: /etc/systemd/system/apt-daily.timer.d
    state: directory
  when:
    apt_timer_oncalendar is defined or
    apt_timer_randomizeddelaysec is defined or
    apt_timer_persistent is defined
  tags:
    - apt
    - timer

- name: apt-daily timer override
  template:
    src: apt-daily.timer.override.conf.j2
    dest: /etc/systemd/system/apt-daily.timer.d/override.conf
  when:
    apt_timer_oncalendar is defined or
    apt_timer_randomizeddelaysec is defined or
    apt_timer_persistent is defined
  notify:
    - systemd reload
  tags:
    - apt
    - timer

- name: remove apt-daily timer override
  file:
    path: /etc/systemd/system/apt-daily.timer.d/override.conf
    state: absent
  when:
    not (
    apt_timer_oncalendar is defined or
    apt_timer_randomizeddelaysec is defined or
    apt_timer_persistent is defined
    )
  notify:
    - systemd reload
  tags:
    - apt
    - timer

- name: remove apt-daily timer override dir
  file:
    path: /etc/systemd/system/apt-daily.timer.d
    state: absent
  when:
    not (
    apt_timer_oncalendar is defined or
    apt_timer_randomizeddelaysec is defined or
    apt_timer_persistent is defined
    )
  tags:
    - apt
    - timer
...
