---
# tasks file for apt
- name: Sources
  ansible.builtin.template:
    src: "sources.list.{{ ansible_lsb.id | default(ansible_os_family) }}.j2"
    dest: /etc/apt/sources.list
    backup: true
    owner: root
    group: root
    mode: 0644
  notify:
    - Update cache
  tags:
    - apt
    - sources.list

- name: Deb822
  when:
    - apt_sources_style is defined
    - apt_sources_style | lower == 'deb822'
  tags:
    - deb822
  block:
    - name: Sources
      ansible.builtin.template:
        src: deb822.sources.j2
        dest: "/etc/apt/sources.list.d/{{ item.name }}.sources"
        backup: true
        owner: root
        group: root
        mode: 0644
      loop: "{{ apt_sources }}"
      notify:
        - Update cache
      tags:
        - apt
        - sources

    - name: Mirrors
      ansible.builtin.template:
        src: deb822_mirrors.list.j2
        dest: "/etc/apt/mirrors/{{ item.name }}.list"
        backup: true
        owner: root
        group: root
        mode: 0644
      loop: "{{ apt_mirrors }}"
      notify:
        - Update cache
      tags:
        - apt
        - mirrors

- name: Dpkg
  ansible.builtin.import_tasks: dpkg.yml

- name: Network options
  ansible.builtin.template:
    src: network.j2
    dest: /etc/apt/apt.conf.d/30network
    owner: root
    group: root
    mode: 0644
  when:
    proxy_env is defined or
    apt_pad is defined
  tags:
    - apt
    - network

- name: Backports
  ansible.builtin.template:
    src: backports.list.j2
    dest: /etc/apt/sources.list.d/backports.list
    owner: root
    group: root
    mode: 0644
  notify:
    - Update cache
  when:
    - apt_backports is defined
    - apt_backports
  tags:
    - apt
    - sources
    - backports

- name: Remove backports.list
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/backports.list
    state: absent
  notify:
    - Update cache
  when:
    apt_backports is not defined or
    not apt_backports
  tags:
    - apt
    - sources
    - backports

- name: Additional repositories preferences
  ansible.builtin.template:
    src: extra.preferences.j2
    dest: "/etc/apt/preferences.d/{{ item.filename }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ apt_repositories }}"
  notify:
    - Regenerate apt caches
  when:
    - apt_repositories is defined
    - item.apt_pin_priority is defined
  tags:
    - apt
    - extra
    - preferences

- name: Additional repositories
  ansible.builtin.apt_repository:
    filename: "{{ item.filename }}"
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
    update_cache: false
  loop: "{{ apt_repositories }}"
  notify:
    - Update cache
  when: apt_repositories is defined
  tags:
    - apt
    - sources.list.d
    - repositories

- name: Daily timer override dir
  ansible.builtin.file:
    path: /etc/systemd/system/apt-daily.timer.d
    state: directory
    owner: root
    group: root
    mode: 0755
  when:
    apt_timer_oncalendar is defined or
    apt_timer_randomizeddelaysec is defined or
    apt_timer_persistent is defined
  tags:
    - apt
    - timer

- name: Daily timer override
  ansible.builtin.template:
    src: apt-daily.timer.override.conf.j2
    dest: /etc/systemd/system/apt-daily.timer.d/override.conf
    owner: root
    group: root
    mode: 0644
  when:
    apt_timer_oncalendar is defined or
    apt_timer_randomizeddelaysec is defined or
    apt_timer_persistent is defined
  notify:
    - Systemd reload
  tags:
    - apt
    - timer

- name: Remove apt-daily timer override
  ansible.builtin.file:
    path: /etc/systemd/system/apt-daily.timer.d/override.conf
    state: absent
  when:
    not (
    apt_timer_oncalendar is defined or
    apt_timer_randomizeddelaysec is defined or
    apt_timer_persistent is defined
    )
  notify:
    - Systemd reload
  tags:
    - apt
    - timer

- name: Remove apt-daily timer override dir
  ansible.builtin.file:
    path: /etc/systemd/system/apt-daily.timer.d
    state: absent
  when:
    not (
    apt_timer_oncalendar is defined or
    apt_timer_randomizeddelaysec is defined or
    apt_timer_persistent is defined
    )
  tags:
    - apt
    - timer
