---
# tasks file for apt
- name: "apt.conf"
  template:
    src: "apt.conf.j2"
    dest: '/etc/apt/apt.conf'
    backup: 'yes'
    owner: root
    group: root
    mode: 0644
  when:
    - apt_codename is defined
    - apt_codename != 'testing'
  notify:
    - update cache
  tags:
   - apt
   - conf

- name: "sources.list"
  template:
    src: "sources.list.{{ ansible_lsb['id'] }}.j2"
    dest: '/etc/apt/sources.list'
    backup: 'yes'
    owner: root
    group: root
    mode: 0644
  notify:
    - update cache
  tags:
    - apt
    - sources

- name: "dpkg options"
  template:
    src: 'dpkg_options.j2'
    dest: '/etc/apt/apt.conf.d/80dpkg'
  tags:
    - apt
    - dpkg
    - options

- name: "check for noexec /tmp"
  shell: mount|grep -w /tmp|grep -q noexec
  register: tmp_noexec
  tags:
    - apt
    - dpkg
    - tmp

- name: "dpkg options for noexec /tmp"
  template:
    src: 'dpkg_tmp.j2'
    dest: '/etc/apt/apt.conf.d/81dpkg'
  when: tmp_noexec is success
  tags:
    - apt
    - dpkg
    - tmp
...
