---
# tasks file for apt
- name: "apt.conf"
  template:
    src: "apt.conf.j2"
    dest: '/etc/apt/apt.conf'
    backup: 'yes'
    owner: root
    group: root
    mode: 0644
  tags:
   - apt
   - conf

- name: "sources.list"
  template:
    src: "sources.list.{{ ansible_lsb['id'] }}.j2"
    dest: '/etc/apt/sources.list'
    backup: 'yes'
    owner: root
    group: root
    mode: 0644
  tags:
    - apt
    - sources

- name: "dpkg options"
  template:
    src: 'dpkg.j2'
    dest: '/etc/apt/apt.conf.d/80dpkg'
  tags:
    - apt
    - dpkg
...
