---
# handlers file for apt
- name: Update cache
  ansible.builtin.apt:
    update_cache: true
  when:
    - not ansible_check_mode

- name: Regenerate apt caches
  ansible.builtin.command: apt-cache gencaches
  when:
    - not ansible_check_mode
  changed_when: false

- name: Systemd reload
  ansible.builtin.systemd:
    daemon_reload: true
  when:
    - not ansible_check_mode
